### ISSUE TITLE
first hit of A or STEP is omitted

### ISSUE THREAD

**Issue by StefanKellerAC** [gerhardf1/F3F-Timer#4]
It seems that (with v 0.9) the first step is omitted in single and F3B mode.
When flying, the time starts only after the third hit of Base A, after returning from B.
This is also the case when simulating with the step button in the app.
Nothing happens pushing STEP the first time after Start.

maybe this is related to:
2020-01-19: V0.2 released: bugfix BaseA-Counter = 3 leads to lap 1

**Comment by gerhardf1** [comment]
Hello,
if you use the button "STEP" you only have to use this button. You don't need to use button "Start" or "Reset" as long as you are going throw the whole cycle.

regards
Gerhard

**Comment by StefanKellerAC** [comment]
The error occurs also when using the pi-cams.
Using the STEP button was for testing/verifying the behavior.

**Comment by gerhardf1** [comment]
When using picams you have to start the 30s countdown by pressing "Start".
At the first "Turn" signal from picam Base A the model is "off course".
At the second "Turn" signal from picam Base A the model is "on course" and the timer starts.

You can test the system also without picams by using the App "F3FTimerRemoteSwitch" (https://github.com/gerhardf1/F3F-Timer/tree/master/F3FTimerRemoteSwitch). Install the app on 2 further mobilephones and connect them to the "F3FTimer" App.
The Button "TURN" at the "F3FTimerRemoteSwitch" simulates a Turn signal from picam.

regards
Gerhard
